# Generated by Django 4.2.15 on 2024-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=15)),
                ('rePassword', models.CharField(max_length=15)),
                ('isTermsAgree', models.BooleanField()),
            ],
        ),
    ]
