# Generated by Django 4.2.15 on 2024-08-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOpr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
