# Generated by Django 4.2.15 on 2024-08-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOpr', '0002_alter_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
